# Form implementation generated from reading ui file 'fund.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FundWindow(object):
    def setupUi(self, FundWindow):
        FundWindow.setObjectName("FundWindow")
        FundWindow.resize(1326, 874)
        self.centralwidget = QtWidgets.QWidget(parent=FundWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(5, 5, 1316, 866))
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.line = QtWidgets.QFrame(parent=self.groupBox)
        self.line.setGeometry(QtCore.QRect(1, 360, 1313, 1))
        self.line.setMinimumSize(QtCore.QSize(0, 0))
        self.line.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.line.setStyleSheet("color: red;\n"
"background-color: red;\n"
"")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.fund_l_name = QtWidgets.QLabel(parent=self.groupBox)
        self.fund_l_name.setGeometry(QtCore.QRect(960, 370, 60, 25))
        self.fund_l_name.setObjectName("fund_l_name")
        self.fund_cb = QtWidgets.QComboBox(parent=self.groupBox)
        self.fund_cb.setGeometry(QtCore.QRect(1020, 370, 100, 25))
        self.fund_cb.setObjectName("fund_cb")
        self.report_cb = QtWidgets.QComboBox(parent=self.groupBox)
        self.report_cb.setGeometry(QtCore.QRect(1190, 370, 120, 25))
        self.report_cb.setObjectName("report_cb")
        self.report_l_name = QtWidgets.QLabel(parent=self.groupBox)
        self.report_l_name.setGeometry(QtCore.QRect(1130, 370, 60, 25))
        self.report_l_name.setObjectName("report_l_name")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 100, 25))
        self.label_4.setStyleSheet("color: red;\n"
"")
        self.label_4.setObjectName("label_4")
        self.ihdetail = QtWidgets.QTableView(parent=self.groupBox)
        self.ihdetail.setGeometry(QtCore.QRect(20, 40, 1291, 316))
        self.ihdetail.setObjectName("ihdetail")
        self.phdetail = QtWidgets.QTableView(parent=self.groupBox)
        self.phdetail.setGeometry(QtCore.QRect(20, 400, 1291, 451))
        self.phdetail.setObjectName("phdetail")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 370, 100, 25))
        self.label_5.setStyleSheet("color: red;\n"
"")
        self.label_5.setObjectName("label_5")
        self.create_date = QtWidgets.QLabel(parent=self.groupBox)
        self.create_date.setGeometry(QtCore.QRect(150, 10, 200, 25))
        self.create_date.setObjectName("create_date")
        FundWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(FundWindow)
        QtCore.QMetaObject.connectSlotsByName(FundWindow)

    def retranslateUi(self, FundWindow):
        _translate = QtCore.QCoreApplication.translate
        FundWindow.setWindowTitle(_translate("FundWindow", "MainWindow"))
        self.fund_l_name.setText(_translate("FundWindow", "持股机构："))
        self.report_l_name.setText(_translate("FundWindow", "报告日期："))
        self.label_4.setText(_translate("FundWindow", "持股机构总览"))
        self.label_5.setText(_translate("FundWindow", "持仓机构明细"))
        self.create_date.setText(_translate("FundWindow", "采集时间：2025/10/24 15:35:33"))
