# Form implementation generated from reading ui file 'mainCapitalDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainCapitalDialog(object):
    def setupUi(self, mainCapitalDialog):
        mainCapitalDialog.setObjectName("mainCapitalDialog")
        mainCapitalDialog.resize(1371, 818)
        self.formLayoutWidget = QtWidgets.QWidget(parent=mainCapitalDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1351, 741))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.mainCapitalTree = QtWidgets.QTreeView(parent=self.formLayoutWidget)
        self.mainCapitalTree.setObjectName("mainCapitalTree")
        self.mainCapitalTree.header().setHighlightSections(False)
        self.mainCapitalTree.header().setStretchLastSection(True)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.mainCapitalTree)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.formLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1085, 737))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalStackedWidget = QtWidgets.QStackedWidget(parent=self.scrollAreaWidgetContents)
        self.verticalStackedWidget.setGeometry(QtCore.QRect(0, 0, 1086, 820))
        self.verticalStackedWidget.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.verticalStackedWidget.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.verticalStackedWidget.setObjectName("verticalStackedWidget")
        self.pageOne = QtWidgets.QWidget()
        self.pageOne.setObjectName("pageOne")
        self.tableView = QtWidgets.QTableView(parent=self.pageOne)
        self.tableView.setGeometry(QtCore.QRect(-1, -1, 1086, 819))
        self.tableView.setObjectName("tableView")
        self.verticalStackedWidget.addWidget(self.pageOne)
        self.pageTwo = QtWidgets.QWidget()
        self.pageTwo.setObjectName("pageTwo")
        self.widget = QtWidgets.QWidget(parent=self.pageTwo)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1086, 819))
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 1091, 741))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalStackedWidget.addWidget(self.pageTwo)
        self.pageThree = QtWidgets.QWidget()
        self.pageThree.setObjectName("pageThree")
        self.widget_2 = QtWidgets.QWidget(parent=self.pageThree)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 1086, 819))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.widget_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 1091, 741))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.detailInfo = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.detailInfo.setContentsMargins(0, 0, 0, 0)
        self.detailInfo.setObjectName("detailInfo")
        self.verticalStackedWidget.addWidget(self.pageThree)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.scrollArea)
        self.undoView = QtWidgets.QUndoView(parent=mainCapitalDialog)
        self.undoView.setGeometry(QtCore.QRect(10, 758, 1351, 51))
        self.undoView.setObjectName("undoView")
        self.allSshyCharts = QtWidgets.QPushButton(parent=mainCapitalDialog)
        self.allSshyCharts.setGeometry(QtCore.QRect(950, 766, 75, 30))
        self.allSshyCharts.setStyleSheet("QPushButton {\n"
"        border: 1px solid #000000;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.allSshyCharts.setObjectName("allSshyCharts")
        self.nav_option = QtWidgets.QLabel(parent=mainCapitalDialog)
        self.nav_option.setGeometry(QtCore.QRect(20, 770, 300, 26))
        self.nav_option.setText("")
        self.nav_option.setObjectName("nav_option")
        self.showType = QtWidgets.QComboBox(parent=mainCapitalDialog)
        self.showType.setGeometry(QtCore.QRect(320, 770, 125, 26))
        self.showType.setObjectName("showType")
        self.printDialog = QtWidgets.QPushButton(parent=mainCapitalDialog)
        self.printDialog.setGeometry(QtCore.QRect(1150, 766, 95, 30))
        self.printDialog.setStyleSheet("QPushButton {\n"
"        border: 1px solid #000000;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.printDialog.setObjectName("printDialog")
        self.printPreview = QtWidgets.QPushButton(parent=mainCapitalDialog)
        self.printPreview.setGeometry(QtCore.QRect(1040, 766, 95, 30))
        self.printPreview.setStyleSheet("QPushButton {\n"
"        border: 1px solid #000000;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.printPreview.setObjectName("printPreview")

        self.retranslateUi(mainCapitalDialog)
        self.verticalStackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(mainCapitalDialog)

    def retranslateUi(self, mainCapitalDialog):
        _translate = QtCore.QCoreApplication.translate
        mainCapitalDialog.setWindowTitle(_translate("mainCapitalDialog", "Form"))
        self.allSshyCharts.setText(_translate("mainCapitalDialog", "所有行业"))
        self.printDialog.setText(_translate("mainCapitalDialog", "打印"))
        self.printDialog.setShortcut(_translate("mainCapitalDialog", "Ctrl+P"))
        self.printPreview.setText(_translate("mainCapitalDialog", "预览"))
        self.printPreview.setShortcut(_translate("mainCapitalDialog", "Ctrl+W"))
