# Form implementation generated from reading ui file 'WLW.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WLW(object):
    def setupUi(self, WLW):
        WLW.setObjectName("WLW")
        WLW.resize(1532, 836)
        self.centralwidget = QtWidgets.QWidget(parent=WLW)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(5, 0, 1531, 791))
        self.tabWidget.setStyleSheet("/* 标签栏整体样式 */\n"
"QTabBar {\n"
"    background: #f8f9fa;\n"
"    border-bottom: 1px solid #dee2e6;\n"
"}\n"
"\n"
"/* 未选中标签样式 */\n"
"QTabBar::tab {\n"
"    background: #e9ecef;\n"
"    color: #495057;\n"
"    border: 1px solid #dee2e6;\n"
"    border-bottom-color: #dee2e6;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    padding: 2px 4px;\n"
"    margin-right: 2px;\n"
"    min-width: 60px;\n"
"}\n"
"\n"
"/* 选中标签样式 */\n"
"QTabBar::tab:selected {\n"
"    background: #ffffff;\n"
"    /* color: #0d6efd; */\n"
"    color: rgb(255, 0, 0);\n"
"    border-color: #dee2e6;\n"
"    border-bottom-color: #ffffff;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* 悬停标签样式 */\n"
"QTabBar::tab:hover {\n"
"    background: #dee2e6;\n"
"}\n"
"\n"
"/* 内容面板样式 */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #dee2e6;\n"
"    border-top: none;\n"
"    margin-top: -1px;\n"
"    background: #ffffff;\n"
"}")
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.stockInfo = QtWidgets.QWidget()
        self.stockInfo.setObjectName("stockInfo")
        self.groupBox = QtWidgets.QGroupBox(parent=self.stockInfo)
        self.groupBox.setGeometry(QtCore.QRect(5, 5, 1508, 101))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(25, 20, 55, 22))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.saleDateFrom = AutoSetDateEdit(parent=self.groupBox)
        self.saleDateFrom.setGeometry(QtCore.QRect(90, 20, 160, 22))
        self.saleDateFrom.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 7, 1), QtCore.QTime(0, 0, 0)))
        self.saleDateFrom.setTime(QtCore.QTime(0, 0, 0))
        self.saleDateFrom.setObjectName("saleDateFrom")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(255, 20, 20, 22))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.saleDateTo = AutoSetDateEdit(parent=self.groupBox)
        self.saleDateTo.setGeometry(QtCore.QRect(280, 20, 160, 22))
        self.saleDateTo.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 7, 1), QtCore.QTime(0, 0, 0)))
        self.saleDateTo.setTime(QtCore.QTime(0, 0, 0))
        self.saleDateTo.setObjectName("saleDateTo")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(460, 20, 45, 22))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.stockNo = AutoSetNumberLineEdit(parent=self.groupBox)
        self.stockNo.setGeometry(QtCore.QRect(510, 20, 81, 22))
        self.stockNo.setObjectName("stockNo")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(610, 20, 55, 22))
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.stockName = QtWidgets.QLineEdit(parent=self.groupBox)
        self.stockName.setGeometry(QtCore.QRect(670, 20, 80, 22))
        self.stockName.setObjectName("stockName")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(770, 20, 45, 22))
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.condition_lbs = QtWidgets.QComboBox(parent=self.groupBox)
        self.condition_lbs.setGeometry(QtCore.QRect(820, 20, 45, 22))
        self.condition_lbs.setObjectName("condition_lbs")
        self.lianBanShu = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lianBanShu.setGeometry(QtCore.QRect(880, 20, 61, 22))
        self.lianBanShu.setObjectName("lianBanShu")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(960, 20, 60, 22))
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.condition_ztcs = QtWidgets.QComboBox(parent=self.groupBox)
        self.condition_ztcs.setGeometry(QtCore.QRect(1030, 20, 45, 22))
        self.condition_ztcs.setObjectName("condition_ztcs")
        self.zhangTingCiShu = QtWidgets.QLineEdit(parent=self.groupBox)
        self.zhangTingCiShu.setGeometry(QtCore.QRect(1090, 20, 71, 22))
        self.zhangTingCiShu.setObjectName("zhangTingCiShu")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(1190, 20, 45, 22))
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.condition_hsl = QtWidgets.QComboBox(parent=self.groupBox)
        self.condition_hsl.setGeometry(QtCore.QRect(1240, 20, 45, 22))
        self.condition_hsl.setObjectName("condition_hsl")
        self.huanShouLv = QtWidgets.QLineEdit(parent=self.groupBox)
        self.huanShouLv.setGeometry(QtCore.QRect(1300, 20, 51, 22))
        self.huanShouLv.setObjectName("huanShouLv")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(25, 60, 55, 22))
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.suoShuHangYe = QtWidgets.QLineEdit(parent=self.groupBox)
        self.suoShuHangYe.setGeometry(QtCore.QRect(90, 60, 121, 22))
        self.suoShuHangYe.setObjectName("suoShuHangYe")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(250, 60, 55, 22))
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.stock_stockType = QtWidgets.QComboBox(parent=self.groupBox)
        self.stock_stockType.setGeometry(QtCore.QRect(318, 60, 121, 22))
        self.stock_stockType.setObjectName("stock_stockType")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(460, 60, 45, 22))
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.youzi_comboBox = QtWidgets.QComboBox(parent=self.groupBox)
        self.youzi_comboBox.setGeometry(QtCore.QRect(510, 60, 81, 22))
        self.youzi_comboBox.setObjectName("youzi_comboBox")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(610, 60, 55, 22))
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.le_ztzt = QtWidgets.QLineEdit(parent=self.groupBox)
        self.le_ztzt.setGeometry(QtCore.QRect(670, 60, 80, 22))
        self.le_ztzt.setObjectName("le_ztzt")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(770, 60, 45, 22))
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.condition_zxj = QtWidgets.QComboBox(parent=self.groupBox)
        self.condition_zxj.setGeometry(QtCore.QRect(820, 60, 45, 22))
        self.condition_zxj.setObjectName("condition_zxj")
        self.le_zxj = QtWidgets.QLineEdit(parent=self.groupBox)
        self.le_zxj.setGeometry(QtCore.QRect(880, 60, 61, 22))
        self.le_zxj.setObjectName("le_zxj")
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(960, 60, 60, 22))
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.condtion_zbcs = QtWidgets.QComboBox(parent=self.groupBox)
        self.condtion_zbcs.setGeometry(QtCore.QRect(1030, 60, 45, 22))
        self.condtion_zbcs.setObjectName("condtion_zbcs")
        self.zhaBanCiShu = QtWidgets.QLineEdit(parent=self.groupBox)
        self.zhaBanCiShu.setGeometry(QtCore.QRect(1090, 60, 71, 22))
        self.zhaBanCiShu.setObjectName("zhaBanCiShu")
        self.stockSubmit = QtWidgets.QPushButton(parent=self.groupBox)
        self.stockSubmit.setGeometry(QtCore.QRect(1230, 60, 75, 30))
        self.stockSubmit.setStyleSheet("QPushButton {\n"
"        border: 1px solid #000000;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.stockSubmit.setObjectName("stockSubmit")
        self.stockClear = QtWidgets.QPushButton(parent=self.groupBox)
        self.stockClear.setGeometry(QtCore.QRect(1310, 60, 75, 30))
        self.stockClear.setStyleSheet("QPushButton {\n"
"        border: 1px solid #000000;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.stockClear.setObjectName("stockClear")
        self.stockDialog = QtWidgets.QPushButton(parent=self.groupBox)
        self.stockDialog.setGeometry(QtCore.QRect(1390, 60, 101, 30))
        self.stockDialog.setStyleSheet("QPushButton {\n"
"        border: 1px solid #000000;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.stockDialog.setObjectName("stockDialog")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.stockInfo)
        self.groupBox_2.setGeometry(QtCore.QRect(5, 110, 1508, 650))
        self.groupBox_2.setObjectName("groupBox_2")
        self.count_number = QtWidgets.QLabel(parent=self.groupBox_2)
        self.count_number.setGeometry(QtCore.QRect(20, 22, 141, 25))
        self.count_number.setObjectName("count_number")
        self.showStockTable = QtWidgets.QTableView(parent=self.groupBox_2)
        self.showStockTable.setGeometry(QtCore.QRect(3, 55, 1502, 590))
        self.showStockTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.showStockTable.setObjectName("showStockTable")
        self.showStockTable.horizontalHeader().setMinimumSectionSize(25)
        self.showStockTable.verticalHeader().setMinimumSectionSize(23)
        self.plateStockNo = QtWidgets.QLabel(parent=self.groupBox_2)
        self.plateStockNo.setGeometry(QtCore.QRect(1330, 22, 80, 25))
        self.plateStockNo.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.plateStockNo.setMidLineWidth(0)
        self.plateStockNo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.plateStockNo.setObjectName("plateStockNo")
        self.nextStockPage = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.nextStockPage.setGeometry(QtCore.QRect(1420, 22, 30, 25))
        self.nextStockPage.setStyleSheet("QPushButton {\n"
"        \n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.nextStockPage.setText("")
        self.nextStockPage.setObjectName("nextStockPage")
        self.upStockPage = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.upStockPage.setGeometry(QtCore.QRect(1290, 22, 30, 25))
        self.upStockPage.setStyleSheet("QPushButton {\n"
"        \n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.upStockPage.setText("")
        self.upStockPage.setObjectName("upStockPage")
        self.tabWidget.addTab(self.stockInfo, "")
        self.plateFund = QtWidgets.QWidget()
        self.plateFund.setObjectName("plateFund")
        self.groupBox_8 = QtWidgets.QGroupBox(parent=self.plateFund)
        self.groupBox_8.setGeometry(QtCore.QRect(5, 355, 1508, 405))
        self.groupBox_8.setObjectName("groupBox_8")
        self.plateFund_count_number = QtWidgets.QLabel(parent=self.groupBox_8)
        self.plateFund_count_number.setGeometry(QtCore.QRect(20, 20, 141, 25))
        self.plateFund_count_number.setObjectName("plateFund_count_number")
        self.plateFund_showStockTable = QtWidgets.QTableView(parent=self.groupBox_8)
        self.plateFund_showStockTable.setGeometry(QtCore.QRect(3, 50, 1502, 350))
        self.plateFund_showStockTable.setObjectName("plateFund_showStockTable")
        self.label_14 = QtWidgets.QLabel(parent=self.groupBox_8)
        self.label_14.setGeometry(QtCore.QRect(200, 20, 141, 25))
        self.label_14.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 11pt \"楷体\";")
        self.label_14.setObjectName("label_14")
        self.plateFundInput = QtWidgets.QLabel(parent=self.groupBox_8)
        self.plateFundInput.setGeometry(QtCore.QRect(370, 20, 151, 25))
        self.plateFundInput.setStyleSheet("color:red;\n"
"font: 11pt \"楷体\";")
        self.plateFundInput.setText("")
        self.plateFundInput.setObjectName("plateFundInput")
        self.plateFundOutput = QtWidgets.QLabel(parent=self.groupBox_8)
        self.plateFundOutput.setGeometry(QtCore.QRect(550, 20, 151, 25))
        self.plateFundOutput.setStyleSheet("color:green;\n"
"font: 11pt \"楷体\";")
        self.plateFundOutput.setText("")
        self.plateFundOutput.setObjectName("plateFundOutput")
        self.upPlateFundPage = QtWidgets.QPushButton(parent=self.groupBox_8)
        self.upPlateFundPage.setGeometry(QtCore.QRect(1290, 22, 30, 25))
        self.upPlateFundPage.setStyleSheet("QPushButton {\n"
"        \n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.upPlateFundPage.setText("")
        self.upPlateFundPage.setObjectName("upPlateFundPage")
        self.plateFundPageNo = QtWidgets.QLabel(parent=self.groupBox_8)
        self.plateFundPageNo.setGeometry(QtCore.QRect(1330, 22, 80, 25))
        self.plateFundPageNo.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.plateFundPageNo.setText("")
        self.plateFundPageNo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.plateFundPageNo.setObjectName("plateFundPageNo")
        self.nextPlateFundPage = QtWidgets.QPushButton(parent=self.groupBox_8)
        self.nextPlateFundPage.setGeometry(QtCore.QRect(1420, 22, 30, 25))
        self.nextPlateFundPage.setStyleSheet("QPushButton {\n"
"        \n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.nextPlateFundPage.setText("")
        self.nextPlateFundPage.setObjectName("nextPlateFundPage")
        self.groupBox_7 = QtWidgets.QGroupBox(parent=self.plateFund)
        self.groupBox_7.setGeometry(QtCore.QRect(5, 290, 1508, 61))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_31 = QtWidgets.QLabel(parent=self.groupBox_7)
        self.label_31.setGeometry(QtCore.QRect(25, 20, 55, 22))
        self.label_31.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.plateFundDate_From = AutoSetDateEdit(parent=self.groupBox_7)
        self.plateFundDate_From.setGeometry(QtCore.QRect(85, 20, 160, 22))
        self.plateFundDate_From.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 6, 28), QtCore.QTime(0, 0, 0)))
        self.plateFundDate_From.setTime(QtCore.QTime(0, 0, 0))
        self.plateFundDate_From.setObjectName("plateFundDate_From")
        self.label_32 = QtWidgets.QLabel(parent=self.groupBox_7)
        self.label_32.setGeometry(QtCore.QRect(255, 20, 20, 22))
        self.label_32.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.plateFundDate_To = AutoSetDateEdit(parent=self.groupBox_7)
        self.plateFundDate_To.setGeometry(QtCore.QRect(290, 20, 160, 22))
        self.plateFundDate_To.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 6, 28), QtCore.QTime(0, 0, 0)))
        self.plateFundDate_To.setTime(QtCore.QTime(0, 0, 0))
        self.plateFundDate_To.setObjectName("plateFundDate_To")
        self.plateFundSubmit = QtWidgets.QPushButton(parent=self.groupBox_7)
        self.plateFundSubmit.setGeometry(QtCore.QRect(1230, 20, 75, 30))
        self.plateFundSubmit.setStyleSheet("QPushButton {\n"
"        border: 1px solid #000000;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.plateFundSubmit.setObjectName("plateFundSubmit")
        self.plateFundClear = QtWidgets.QPushButton(parent=self.groupBox_7)
        self.plateFundClear.setGeometry(QtCore.QRect(1310, 20, 75, 30))
        self.plateFundClear.setStyleSheet("QPushButton {\n"
"        border: 1px solid #000000;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.plateFundClear.setObjectName("plateFundClear")
        self.plateFund_Name = QtWidgets.QLineEdit(parent=self.groupBox_7)
        self.plateFund_Name.setGeometry(QtCore.QRect(550, 20, 80, 22))
        self.plateFund_Name.setObjectName("plateFund_Name")
        self.plateFund_No = AutoSetNumberLineEdit(parent=self.groupBox_7)
        self.plateFund_No.setGeometry(QtCore.QRect(460, 20, 81, 22))
        self.plateFund_No.setObjectName("plateFund_No")
        self.master_xianJia_n_3 = QtWidgets.QLabel(parent=self.groupBox_7)
        self.master_xianJia_n_3.setGeometry(QtCore.QRect(640, 20, 100, 22))
        self.master_xianJia_n_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.master_xianJia_n_3.setObjectName("master_xianJia_n_3")
        self.plateFund_zljlrje = QtWidgets.QLineEdit(parent=self.groupBox_7)
        self.plateFund_zljlrje.setGeometry(QtCore.QRect(810, 20, 80, 22))
        self.plateFund_zljlrje.setObjectName("plateFund_zljlrje")
        self.plateFund_condition_zljlrje = QtWidgets.QComboBox(parent=self.groupBox_7)
        self.plateFund_condition_zljlrje.setGeometry(QtCore.QRect(750, 20, 45, 22))
        self.plateFund_condition_zljlrje.setObjectName("plateFund_condition_zljlrje")
        self.plateFund_zljlrje_unit = QtWidgets.QComboBox(parent=self.groupBox_7)
        self.plateFund_zljlrje_unit.setGeometry(QtCore.QRect(900, 20, 45, 22))
        self.plateFund_zljlrje_unit.setObjectName("plateFund_zljlrje_unit")
        self.plateFundActivate = QtWidgets.QPushButton(parent=self.groupBox_7)
        self.plateFundActivate.setGeometry(QtCore.QRect(1390, 20, 75, 30))
        self.plateFundActivate.setStyleSheet("QPushButton {\n"
"        border: 1px solid #000000;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.plateFundActivate.setObjectName("plateFundActivate")
        self.groupBox_9 = QtWidgets.QGroupBox(parent=self.plateFund)
        self.groupBox_9.setGeometry(QtCore.QRect(5, 5, 1508, 281))
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.plateFundChartWidget = QtWidgets.QWidget(parent=self.groupBox_9)
        self.plateFundChartWidget.setGeometry(QtCore.QRect(0, 0, 1507, 280))
        self.plateFundChartWidget.setObjectName("plateFundChartWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.plateFundChartWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1491, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.detailInfo = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.detailInfo.setContentsMargins(0, 0, 0, 0)
        self.detailInfo.setObjectName("detailInfo")
        self.tabWidget.addTab(self.plateFund, "")
        self.lncreaseFive = QtWidgets.QWidget()
        self.lncreaseFive.setObjectName("lncreaseFive")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.lncreaseFive)
        self.groupBox_5.setGeometry(QtCore.QRect(5, 5, 1508, 101))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_28 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_28.setGeometry(QtCore.QRect(210, 20, 45, 22))
        self.label_28.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.lncrease_stockNo = AutoSetNumberLineEdit(parent=self.groupBox_5)
        self.lncrease_stockNo.setGeometry(QtCore.QRect(260, 20, 81, 22))
        self.lncrease_stockNo.setObjectName("lncrease_stockNo")
        self.label_29 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(370, 20, 55, 22))
        self.label_29.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.lncrease_stockName = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.lncrease_stockName.setGeometry(QtCore.QRect(430, 20, 80, 22))
        self.lncrease_stockName.setObjectName("lncrease_stockName")
        self.master_hangYe_n_3 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.master_hangYe_n_3.setGeometry(QtCore.QRect(545, 20, 55, 22))
        self.master_hangYe_n_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.master_hangYe_n_3.setObjectName("master_hangYe_n_3")
        self.lncrease_hangYe = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.lncrease_hangYe.setGeometry(QtCore.QRect(610, 20, 121, 22))
        self.lncrease_hangYe.setObjectName("lncrease_hangYe")
        self.label_30 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_30.setGeometry(QtCore.QRect(962, 20, 55, 22))
        self.label_30.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.lncrease_stockType = QtWidgets.QComboBox(parent=self.groupBox_5)
        self.lncrease_stockType.setGeometry(QtCore.QRect(1030, 20, 111, 22))
        self.lncrease_stockType.setObjectName("lncrease_stockType")
        self.lncrease_stockSubmit = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.lncrease_stockSubmit.setGeometry(QtCore.QRect(1230, 60, 75, 30))
        self.lncrease_stockSubmit.setStyleSheet("QPushButton {\n"
"        border: 1px solid #000000;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.lncrease_stockSubmit.setObjectName("lncrease_stockSubmit")
        self.lncrease_stockClear = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.lncrease_stockClear.setGeometry(QtCore.QRect(1310, 60, 75, 30))
        self.lncrease_stockClear.setStyleSheet("QPushButton {\n"
"        border: 1px solid #000000;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.lncrease_stockClear.setObjectName("lncrease_stockClear")
        self.master_xianJia_n_2 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.master_xianJia_n_2.setGeometry(QtCore.QRect(750, 20, 40, 22))
        self.master_xianJia_n_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.master_xianJia_n_2.setObjectName("master_xianJia_n_2")
        self.lncrease_condition_xj = QtWidgets.QComboBox(parent=self.groupBox_5)
        self.lncrease_condition_xj.setGeometry(QtCore.QRect(800, 20, 45, 22))
        self.lncrease_condition_xj.setObjectName("lncrease_condition_xj")
        self.lncrease_xianJia = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.lncrease_xianJia.setGeometry(QtCore.QRect(860, 20, 80, 22))
        self.lncrease_xianJia.setObjectName("lncrease_xianJia")
        self.lncrease_condition_zj = QtWidgets.QComboBox(parent=self.groupBox_5)
        self.lncrease_condition_zj.setGeometry(QtCore.QRect(70, 20, 120, 22))
        self.lncrease_condition_zj.setObjectName("lncrease_condition_zj")
        self.master_xianJia_n_4 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.master_xianJia_n_4.setGeometry(QtCore.QRect(25, 20, 40, 22))
        self.master_xianJia_n_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.master_xianJia_n_4.setObjectName("master_xianJia_n_4")
        self.groupBox_6 = QtWidgets.QGroupBox(parent=self.lncreaseFive)
        self.groupBox_6.setGeometry(QtCore.QRect(5, 110, 1508, 650))
        self.groupBox_6.setObjectName("groupBox_6")
        self.lncrease_count_number = QtWidgets.QLabel(parent=self.groupBox_6)
        self.lncrease_count_number.setGeometry(QtCore.QRect(20, 22, 141, 25))
        self.lncrease_count_number.setObjectName("lncrease_count_number")
        self.lncrease_showStockTable = QtWidgets.QTableView(parent=self.groupBox_6)
        self.lncrease_showStockTable.setGeometry(QtCore.QRect(3, 54, 1502, 591))
        self.lncrease_showStockTable.setObjectName("lncrease_showStockTable")
        self.uplncreasePage = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.uplncreasePage.setGeometry(QtCore.QRect(1290, 22, 30, 25))
        self.uplncreasePage.setStyleSheet("QPushButton {\n"
"        \n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.uplncreasePage.setText("")
        self.uplncreasePage.setObjectName("uplncreasePage")
        self.lncrease_pageNo = QtWidgets.QLabel(parent=self.groupBox_6)
        self.lncrease_pageNo.setGeometry(QtCore.QRect(1330, 22, 80, 25))
        self.lncrease_pageNo.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lncrease_pageNo.setText("")
        self.lncrease_pageNo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lncrease_pageNo.setObjectName("lncrease_pageNo")
        self.nextlncreasePage = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.nextlncreasePage.setGeometry(QtCore.QRect(1420, 22, 30, 25))
        self.nextlncreasePage.setStyleSheet("QPushButton {\n"
"        \n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.nextlncreasePage.setText("")
        self.nextlncreasePage.setObjectName("nextlncreasePage")
        self.label_zf_lncrease = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_zf_lncrease.setGeometry(QtCore.QRect(390, 22, 30, 22))
        self.label_zf_lncrease.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_zf_lncrease.setObjectName("label_zf_lncrease")
        self.combox_sp_lncrease = QtWidgets.QComboBox(parent=self.groupBox_6)
        self.combox_sp_lncrease.setGeometry(QtCore.QRect(610, 22, 111, 22))
        self.combox_sp_lncrease.setObjectName("combox_sp_lncrease")
        self.label_sp_lncrease = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_sp_lncrease.setGeometry(QtCore.QRect(570, 22, 30, 22))
        self.label_sp_lncrease.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_sp_lncrease.setObjectName("label_sp_lncrease")
        self.combox_zf_lncrease = QtWidgets.QComboBox(parent=self.groupBox_6)
        self.combox_zf_lncrease.setGeometry(QtCore.QRect(430, 22, 111, 22))
        self.combox_zf_lncrease.setObjectName("combox_zf_lncrease")
        self.label_zf_lncrease_2 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_zf_lncrease_2.setGeometry(QtCore.QRect(210, 22, 55, 22))
        self.label_zf_lncrease_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_zf_lncrease_2.setObjectName("label_zf_lncrease_2")
        self.combox_sale_lncrease = QtWidgets.QComboBox(parent=self.groupBox_6)
        self.combox_sale_lncrease.setGeometry(QtCore.QRect(270, 22, 111, 22))
        self.combox_sale_lncrease.setObjectName("combox_sale_lncrease")
        self.combox_plate_lncrease = QtWidgets.QComboBox(parent=self.groupBox_6)
        self.combox_plate_lncrease.setGeometry(QtCore.QRect(815, 22, 111, 22))
        self.combox_plate_lncrease.setObjectName("combox_plate_lncrease")
        self.label_sp_lncrease_2 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_sp_lncrease_2.setGeometry(QtCore.QRect(750, 22, 55, 22))
        self.label_sp_lncrease_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_sp_lncrease_2.setObjectName("label_sp_lncrease_2")
        self.tabWidget.addTab(self.lncreaseFive, "")
        self.waringStock = QtWidgets.QWidget()
        self.waringStock.setObjectName("waringStock")
        self.waring_condition = QtWidgets.QGroupBox(parent=self.waringStock)
        self.waring_condition.setGeometry(QtCore.QRect(5, 5, 1508, 101))
        self.waring_condition.setObjectName("waring_condition")
        self.label_20 = QtWidgets.QLabel(parent=self.waring_condition)
        self.label_20.setGeometry(QtCore.QRect(25, 20, 55, 22))
        self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.waringDateFrom = AutoSetDateEdit(parent=self.waring_condition)
        self.waringDateFrom.setGeometry(QtCore.QRect(85, 20, 160, 22))
        self.waringDateFrom.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 6, 29), QtCore.QTime(0, 0, 0)))
        self.waringDateFrom.setTime(QtCore.QTime(0, 0, 0))
        self.waringDateFrom.setObjectName("waringDateFrom")
        self.label_21 = QtWidgets.QLabel(parent=self.waring_condition)
        self.label_21.setGeometry(QtCore.QRect(255, 20, 20, 22))
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.waringDateTo = AutoSetDateEdit(parent=self.waring_condition)
        self.waringDateTo.setGeometry(QtCore.QRect(280, 20, 160, 22))
        self.waringDateTo.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 6, 29), QtCore.QTime(0, 0, 0)))
        self.waringDateTo.setTime(QtCore.QTime(0, 0, 0))
        self.waringDateTo.setObjectName("waringDateTo")
        self.label_22 = QtWidgets.QLabel(parent=self.waring_condition)
        self.label_22.setGeometry(QtCore.QRect(460, 20, 45, 22))
        self.label_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.waring_stockNo = AutoSetNumberLineEdit(parent=self.waring_condition)
        self.waring_stockNo.setGeometry(QtCore.QRect(510, 20, 81, 22))
        self.waring_stockNo.setObjectName("waring_stockNo")
        self.label_23 = QtWidgets.QLabel(parent=self.waring_condition)
        self.label_23.setGeometry(QtCore.QRect(610, 20, 55, 22))
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.waring_stockName = QtWidgets.QLineEdit(parent=self.waring_condition)
        self.waring_stockName.setGeometry(QtCore.QRect(670, 20, 80, 22))
        self.waring_stockName.setObjectName("waring_stockName")
        self.master_hangYe_n_2 = QtWidgets.QLabel(parent=self.waring_condition)
        self.master_hangYe_n_2.setGeometry(QtCore.QRect(775, 20, 55, 22))
        self.master_hangYe_n_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.master_hangYe_n_2.setObjectName("master_hangYe_n_2")
        self.waring_suoShuHangYe = QtWidgets.QLineEdit(parent=self.waring_condition)
        self.waring_suoShuHangYe.setGeometry(QtCore.QRect(840, 20, 121, 22))
        self.waring_suoShuHangYe.setObjectName("waring_suoShuHangYe")
        self.label_25 = QtWidgets.QLabel(parent=self.waring_condition)
        self.label_25.setGeometry(QtCore.QRect(980, 20, 55, 22))
        self.label_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.waring_stockType = QtWidgets.QComboBox(parent=self.waring_condition)
        self.waring_stockType.setGeometry(QtCore.QRect(1050, 20, 111, 22))
        self.waring_stockType.setObjectName("waring_stockType")
        self.waring_stockSubmit = QtWidgets.QPushButton(parent=self.waring_condition)
        self.waring_stockSubmit.setGeometry(QtCore.QRect(1230, 60, 75, 30))
        self.waring_stockSubmit.setStyleSheet("QPushButton {\n"
"        border: 1px solid #000000;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.waring_stockSubmit.setObjectName("waring_stockSubmit")
        self.waring_stockClear = QtWidgets.QPushButton(parent=self.waring_condition)
        self.waring_stockClear.setGeometry(QtCore.QRect(1310, 60, 75, 30))
        self.waring_stockClear.setStyleSheet("QPushButton {\n"
"        border: 1px solid #000000;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.waring_stockClear.setObjectName("waring_stockClear")
        self.waring_showData = QtWidgets.QGroupBox(parent=self.waringStock)
        self.waring_showData.setGeometry(QtCore.QRect(5, 110, 1508, 650))
        self.waring_showData.setObjectName("waring_showData")
        self.waring_count_number = QtWidgets.QLabel(parent=self.waring_showData)
        self.waring_count_number.setGeometry(QtCore.QRect(20, 22, 141, 25))
        self.waring_count_number.setObjectName("waring_count_number")
        self.waring_showStockTable = QtWidgets.QTableView(parent=self.waring_showData)
        self.waring_showStockTable.setGeometry(QtCore.QRect(3, 54, 1502, 591))
        self.waring_showStockTable.setObjectName("waring_showStockTable")
        self.plateWaringNo = QtWidgets.QLabel(parent=self.waring_showData)
        self.plateWaringNo.setGeometry(QtCore.QRect(1330, 22, 80, 25))
        self.plateWaringNo.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.plateWaringNo.setText("")
        self.plateWaringNo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.plateWaringNo.setObjectName("plateWaringNo")
        self.nextWaringPage = QtWidgets.QPushButton(parent=self.waring_showData)
        self.nextWaringPage.setGeometry(QtCore.QRect(1420, 22, 30, 25))
        self.nextWaringPage.setStyleSheet("QPushButton {\n"
"        \n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.nextWaringPage.setText("")
        self.nextWaringPage.setObjectName("nextWaringPage")
        self.upWaringPage = QtWidgets.QPushButton(parent=self.waring_showData)
        self.upWaringPage.setGeometry(QtCore.QRect(1290, 22, 30, 25))
        self.upWaringPage.setStyleSheet("QPushButton {\n"
"        \n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.upWaringPage.setText("")
        self.upWaringPage.setObjectName("upWaringPage")
        self.tabWidget.addTab(self.waringStock, "")
        self.notices = QtWidgets.QWidget()
        self.notices.setObjectName("notices")
        self.notice_search = QtWidgets.QGroupBox(parent=self.notices)
        self.notice_search.setGeometry(QtCore.QRect(5, 5, 1508, 61))
        self.notice_search.setObjectName("notice_search")
        self.label_33 = QtWidgets.QLabel(parent=self.notice_search)
        self.label_33.setGeometry(QtCore.QRect(450, 20, 45, 22))
        self.label_33.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.notice_stockNo = AutoSetNumberLineEdit(parent=self.notice_search)
        self.notice_stockNo.setGeometry(QtCore.QRect(500, 20, 81, 22))
        self.notice_stockNo.setObjectName("notice_stockNo")
        self.label_34 = QtWidgets.QLabel(parent=self.notice_search)
        self.label_34.setGeometry(QtCore.QRect(600, 20, 55, 22))
        self.label_34.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.notice_stockName = QtWidgets.QLineEdit(parent=self.notice_search)
        self.notice_stockName.setGeometry(QtCore.QRect(660, 20, 80, 22))
        self.notice_stockName.setObjectName("notice_stockName")
        self.notice_stockSubmit = QtWidgets.QPushButton(parent=self.notice_search)
        self.notice_stockSubmit.setGeometry(QtCore.QRect(1230, 20, 75, 30))
        self.notice_stockSubmit.setStyleSheet("QPushButton {\n"
"        border: 1px solid #000000;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.notice_stockSubmit.setObjectName("notice_stockSubmit")
        self.notice_stockClear = QtWidgets.QPushButton(parent=self.notice_search)
        self.notice_stockClear.setGeometry(QtCore.QRect(1310, 20, 75, 30))
        self.notice_stockClear.setStyleSheet("QPushButton {\n"
"        border: 1px solid #000000;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.notice_stockClear.setObjectName("notice_stockClear")
        self.label_15 = QtWidgets.QLabel(parent=self.notice_search)
        self.label_15.setGeometry(QtCore.QRect(25, 20, 55, 22))
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.notice_saleDateFrom = AutoSetDateEdit(parent=self.notice_search)
        self.notice_saleDateFrom.setGeometry(QtCore.QRect(85, 20, 160, 22))
        self.notice_saleDateFrom.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 6, 30), QtCore.QTime(0, 0, 0)))
        self.notice_saleDateFrom.setTime(QtCore.QTime(0, 0, 0))
        self.notice_saleDateFrom.setObjectName("notice_saleDateFrom")
        self.notice_saleDateTo = AutoSetDateEdit(parent=self.notice_search)
        self.notice_saleDateTo.setGeometry(QtCore.QRect(275, 20, 160, 22))
        self.notice_saleDateTo.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 6, 28), QtCore.QTime(0, 0, 0)))
        self.notice_saleDateTo.setTime(QtCore.QTime(0, 0, 0))
        self.notice_saleDateTo.setObjectName("notice_saleDateTo")
        self.label_24 = QtWidgets.QLabel(parent=self.notice_search)
        self.label_24.setGeometry(QtCore.QRect(250, 20, 20, 22))
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.notice_myself = QtWidgets.QPushButton(parent=self.notice_search)
        self.notice_myself.setGeometry(QtCore.QRect(1390, 20, 75, 30))
        self.notice_myself.setStyleSheet("QPushButton {\n"
"        border: 1px solid #000000;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        border: 1px solid #FF0000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #00FF00;\n"
"    }")
        self.notice_myself.setObjectName("notice_myself")
        self.notice_showData = QtWidgets.QGroupBox(parent=self.notices)
        self.notice_showData.setGeometry(QtCore.QRect(5, 70, 1508, 695))
        self.notice_showData.setObjectName("notice_showData")
        self.notice_count_number = QtWidgets.QLabel(parent=self.notice_showData)
        self.notice_count_number.setGeometry(QtCore.QRect(20, 22, 141, 25))
        self.notice_count_number.setObjectName("notice_count_number")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.notice_showData)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 50, 1481, 631))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.formLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1215, 627))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalStackedWidget = QtWidgets.QStackedWidget(parent=self.scrollAreaWidgetContents)
        self.verticalStackedWidget.setGeometry(QtCore.QRect(0, 0, 1216, 628))
        self.verticalStackedWidget.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.verticalStackedWidget.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.verticalStackedWidget.setObjectName("verticalStackedWidget")
        self.pageOne = QtWidgets.QWidget()
        self.pageOne.setObjectName("pageOne")
        self.tableView = QtWidgets.QTableView(parent=self.pageOne)
        self.tableView.setGeometry(QtCore.QRect(-1, -1, 1215, 627))
        self.tableView.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.tableView.setObjectName("tableView")
        self.verticalStackedWidget.addWidget(self.pageOne)
        self.pageTwo = QtWidgets.QWidget()
        self.pageTwo.setObjectName("pageTwo")
        self.webWidget = QtWidgets.QWidget(parent=self.pageTwo)
        self.webWidget.setGeometry(QtCore.QRect(1, 1, 1214, 626))
        self.webWidget.setObjectName("webWidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.webWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 1221, 741))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalStackedWidget.addWidget(self.pageTwo)
        self.pageThree = QtWidgets.QWidget()
        self.pageThree.setObjectName("pageThree")
        self.widget_2 = QtWidgets.QWidget(parent=self.pageThree)
        self.widget_2.setGeometry(QtCore.QRect(1, 1, 1214, 626))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.widget_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(-1, -1, 1221, 741))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.detailInfo_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.detailInfo_2.setContentsMargins(0, 0, 0, 0)
        self.detailInfo_2.setObjectName("detailInfo_2")
        self.verticalStackedWidget.addWidget(self.pageThree)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.scrollArea)
        self.noticeCapitalTree = QtWidgets.QTreeView(parent=self.formLayoutWidget)
        self.noticeCapitalTree.setEnabled(True)
        self.noticeCapitalTree.setMinimumSize(QtCore.QSize(256, 0))
        self.noticeCapitalTree.setStyleSheet("QTreeView {\n"
"    border: 1px solid #000000; /* 设置边框宽度为1像素，样式为实线，颜色为黑色 */\n"
"}\n"
"\n"
"QTreeView::item {\n"
"    border: 1px solid #d9d9d9; /* 设置每个item的边框 */\n"
"    padding: 2px; /* 可选：设置内边距 */\n"
"}")
        self.noticeCapitalTree.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.noticeCapitalTree.setLineWidth(0)
        self.noticeCapitalTree.setMidLineWidth(0)
        self.noticeCapitalTree.setObjectName("noticeCapitalTree")
        self.noticeCapitalTree.header().setHighlightSections(False)
        self.noticeCapitalTree.header().setMinimumSectionSize(24)
        self.noticeCapitalTree.header().setStretchLastSection(True)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.noticeCapitalTree)
        self.tabWidget.addTab(self.notices, "")
        WLW.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=WLW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1532, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        self.fenkaicaiji = QtWidgets.QMenu(parent=self.menu)
        self.fenkaicaiji.setObjectName("fenkaicaiji")
        WLW.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=WLW)
        self.statusbar.setObjectName("statusbar")
        WLW.setStatusBar(self.statusbar)
        self.actionCrawlAll = QtGui.QAction(parent=WLW)
        self.actionCrawlAll.setObjectName("actionCrawlAll")
        self.actionServerData = QtGui.QAction(parent=WLW)
        self.actionServerData.setObjectName("actionServerData")
        self.actionHelp = QtGui.QAction(parent=WLW)
        self.actionHelp.setObjectName("actionHelp")
        self.actionDailyLimit = QtGui.QAction(parent=WLW)
        self.actionDailyLimit.setObjectName("actionDailyLimit")
        self.actionMainCapital = QtGui.QAction(parent=WLW)
        self.actionMainCapital.setObjectName("actionMainCapital")
        self.activePlateFund = QtGui.QAction(parent=WLW)
        self.activePlateFund.setObjectName("activePlateFund")
        self.activeIncreaseFive = QtGui.QAction(parent=WLW)
        self.activeIncreaseFive.setObjectName("activeIncreaseFive")
        self.actionStockHolding = QtGui.QAction(parent=WLW)
        self.actionStockHolding.setObjectName("actionStockHolding")
        self.actionNotices = QtGui.QAction(parent=WLW)
        self.actionNotices.setObjectName("actionNotices")
        self.fenkaicaiji.addAction(self.actionDailyLimit)
        self.fenkaicaiji.addSeparator()
        self.fenkaicaiji.addAction(self.activePlateFund)
        self.fenkaicaiji.addSeparator()
        self.fenkaicaiji.addAction(self.activeIncreaseFive)
        self.fenkaicaiji.addSeparator()
        self.fenkaicaiji.addAction(self.actionStockHolding)
        self.fenkaicaiji.addSeparator()
        self.fenkaicaiji.addAction(self.actionNotices)
        self.menu.addAction(self.actionCrawlAll)
        self.menu.addSeparator()
        self.menu.addAction(self.fenkaicaiji.menuAction())
        self.menu.addSeparator()
        self.menu.addAction(self.actionServerData)
        self.menu.addSeparator()
        self.menu.addAction(self.actionHelp)
        self.menu.addSeparator()
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(WLW)
        self.tabWidget.setCurrentIndex(4)
        self.verticalStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WLW)
        WLW.setTabOrder(self.tabWidget, self.saleDateFrom)
        WLW.setTabOrder(self.saleDateFrom, self.saleDateTo)
        WLW.setTabOrder(self.saleDateTo, self.stockNo)
        WLW.setTabOrder(self.stockNo, self.stockName)
        WLW.setTabOrder(self.stockName, self.condition_lbs)
        WLW.setTabOrder(self.condition_lbs, self.lianBanShu)
        WLW.setTabOrder(self.lianBanShu, self.condition_ztcs)
        WLW.setTabOrder(self.condition_ztcs, self.zhangTingCiShu)
        WLW.setTabOrder(self.zhangTingCiShu, self.condition_hsl)
        WLW.setTabOrder(self.condition_hsl, self.huanShouLv)
        WLW.setTabOrder(self.huanShouLv, self.suoShuHangYe)
        WLW.setTabOrder(self.suoShuHangYe, self.stock_stockType)
        WLW.setTabOrder(self.stock_stockType, self.youzi_comboBox)
        WLW.setTabOrder(self.youzi_comboBox, self.le_ztzt)
        WLW.setTabOrder(self.le_ztzt, self.condition_zxj)
        WLW.setTabOrder(self.condition_zxj, self.le_zxj)
        WLW.setTabOrder(self.le_zxj, self.condtion_zbcs)
        WLW.setTabOrder(self.condtion_zbcs, self.zhaBanCiShu)
        WLW.setTabOrder(self.zhaBanCiShu, self.stockSubmit)
        WLW.setTabOrder(self.stockSubmit, self.stockClear)
        WLW.setTabOrder(self.stockClear, self.stockDialog)
        WLW.setTabOrder(self.stockDialog, self.showStockTable)
        WLW.setTabOrder(self.showStockTable, self.waringDateFrom)
        WLW.setTabOrder(self.waringDateFrom, self.waringDateTo)
        WLW.setTabOrder(self.waringDateTo, self.waring_stockNo)
        WLW.setTabOrder(self.waring_stockNo, self.waring_stockName)
        WLW.setTabOrder(self.waring_stockName, self.waring_suoShuHangYe)
        WLW.setTabOrder(self.waring_suoShuHangYe, self.waring_stockType)
        WLW.setTabOrder(self.waring_stockType, self.waring_stockSubmit)
        WLW.setTabOrder(self.waring_stockSubmit, self.waring_stockClear)
        WLW.setTabOrder(self.waring_stockClear, self.waring_showStockTable)

    def retranslateUi(self, WLW):
        _translate = QtCore.QCoreApplication.translate
        WLW.setWindowTitle(_translate("WLW", "MainWindow"))
        self.groupBox.setTitle(_translate("WLW", "检索条件"))
        self.label.setText(_translate("WLW", "交易日期"))
        self.saleDateFrom.setDisplayFormat(_translate("WLW", "yyyy年MM月dd日"))
        self.label_2.setText(_translate("WLW", "至"))
        self.saleDateTo.setDisplayFormat(_translate("WLW", "yyyy年MM月dd日"))
        self.label_3.setText(_translate("WLW", "股票No"))
        self.label_4.setText(_translate("WLW", "股票名称"))
        self.label_5.setText(_translate("WLW", "连板数"))
        self.label_6.setText(_translate("WLW", "涨停次数"))
        self.label_7.setText(_translate("WLW", "换手率"))
        self.label_8.setText(_translate("WLW", "所属行业"))
        self.label_9.setText(_translate("WLW", "风险种类"))
        self.label_10.setText(_translate("WLW", "游资"))
        self.label_11.setText(_translate("WLW", "涨停主题"))
        self.label_12.setText(_translate("WLW", "最新价"))
        self.label_13.setText(_translate("WLW", "炸板次数"))
        self.stockSubmit.setText(_translate("WLW", "检索"))
        self.stockClear.setText(_translate("WLW", "清除"))
        self.stockDialog.setText(_translate("WLW", "分类显示"))
        self.groupBox_2.setTitle(_translate("WLW", "检索结果"))
        self.count_number.setText(_translate("WLW", "一共110件数据"))
        self.plateStockNo.setText(_translate("WLW", "第三页"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.stockInfo), _translate("WLW", "涨停板"))
        self.groupBox_8.setTitle(_translate("WLW", "检索结果"))
        self.plateFund_count_number.setText(_translate("WLW", "一共110件数据"))
        self.label_14.setText(_translate("WLW", "B：净流入"))
        self.groupBox_7.setTitle(_translate("WLW", "检索条件"))
        self.label_31.setText(_translate("WLW", "交易日期"))
        self.plateFundDate_From.setDisplayFormat(_translate("WLW", "yyyy年MM月dd日"))
        self.label_32.setText(_translate("WLW", "至"))
        self.plateFundDate_To.setDisplayFormat(_translate("WLW", "yyyy年MM月dd日"))
        self.plateFundSubmit.setText(_translate("WLW", "检索"))
        self.plateFundClear.setText(_translate("WLW", "清除"))
        self.plateFund_Name.setPlaceholderText(_translate("WLW", "板块名称"))
        self.plateFund_No.setPlaceholderText(_translate("WLW", "板块代码"))
        self.master_xianJia_n_3.setText(_translate("WLW", "主力净流入(净额)"))
        self.plateFundActivate.setText(_translate("WLW", "概念"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plateFund), _translate("WLW", "板块资金"))
        self.groupBox_5.setTitle(_translate("WLW", "检索条件"))
        self.label_28.setText(_translate("WLW", "股票No"))
        self.label_29.setText(_translate("WLW", "股票名称"))
        self.master_hangYe_n_3.setText(_translate("WLW", "所属行业"))
        self.label_30.setText(_translate("WLW", "风险种类"))
        self.lncrease_stockSubmit.setText(_translate("WLW", "检索"))
        self.lncrease_stockClear.setText(_translate("WLW", "清除"))
        self.master_xianJia_n_2.setText(_translate("WLW", "最新价"))
        self.master_xianJia_n_4.setText(_translate("WLW", "最近"))
        self.groupBox_6.setTitle(_translate("WLW", "检索结果"))
        self.lncrease_count_number.setText(_translate("WLW", "一共110件数据"))
        self.label_zf_lncrease.setText(_translate("WLW", "涨幅"))
        self.label_sp_lncrease.setText(_translate("WLW", "股价"))
        self.label_zf_lncrease_2.setText(_translate("WLW", "交易日期"))
        self.label_sp_lncrease_2.setText(_translate("WLW", "上榜统计"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.lncreaseFive), _translate("WLW", "涨幅(4%)以上"))
        self.waring_condition.setTitle(_translate("WLW", "检索条件"))
        self.label_20.setText(_translate("WLW", "个股日期"))
        self.waringDateFrom.setDisplayFormat(_translate("WLW", "yyyy年MM月dd日"))
        self.label_21.setText(_translate("WLW", "至"))
        self.waringDateTo.setDisplayFormat(_translate("WLW", "yyyy年MM月dd日"))
        self.label_22.setText(_translate("WLW", "股票No"))
        self.label_23.setText(_translate("WLW", "股票名称"))
        self.master_hangYe_n_2.setText(_translate("WLW", "所属行业"))
        self.label_25.setText(_translate("WLW", "风险种类"))
        self.waring_stockSubmit.setText(_translate("WLW", "检索"))
        self.waring_stockClear.setText(_translate("WLW", "清除"))
        self.waring_showData.setTitle(_translate("WLW", "检索结果"))
        self.waring_count_number.setText(_translate("WLW", "一共110件数据"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.waringStock), _translate("WLW", "风险个股"))
        self.notice_search.setTitle(_translate("WLW", "检索条件"))
        self.label_33.setText(_translate("WLW", "股票No"))
        self.label_34.setText(_translate("WLW", "股票名称"))
        self.notice_stockSubmit.setText(_translate("WLW", "检索"))
        self.notice_stockClear.setText(_translate("WLW", "清除"))
        self.label_15.setText(_translate("WLW", "公告日期"))
        self.notice_saleDateFrom.setDisplayFormat(_translate("WLW", "yyyy年MM月dd日"))
        self.notice_saleDateTo.setDisplayFormat(_translate("WLW", "yyyy年MM月dd日"))
        self.label_24.setText(_translate("WLW", "至"))
        self.notice_myself.setText(_translate("WLW", "投资"))
        self.notice_showData.setTitle(_translate("WLW", "检索结果"))
        self.notice_count_number.setText(_translate("WLW", "一共110件数据"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.notices), _translate("WLW", "公告"))
        self.menu.setTitle(_translate("WLW", "数据采集"))
        self.fenkaicaiji.setTitle(_translate("WLW", "分开采集"))
        self.actionCrawlAll.setText(_translate("WLW", "采集所有"))
        self.actionServerData.setText(_translate("WLW", "风险个股"))
        self.actionHelp.setText(_translate("WLW", "说明"))
        self.actionDailyLimit.setText(_translate("WLW", "日涨停"))
        self.actionMainCapital.setText(_translate("WLW", "主力资金"))
        self.activePlateFund.setText(_translate("WLW", "板块资金"))
        self.activeIncreaseFive.setText(_translate("WLW", "涨幅(4%)以上"))
        self.actionStockHolding.setText(_translate("WLW", "机构持股"))
        self.actionNotices.setText(_translate("WLW", "公告"))
from WLW.StockBase.AutoSetNumberLineEdit import AutoSetNumberLineEdit
from WLW.StockBase.DateEditEx import AutoSetDateEdit
